version: "2"

checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 1024
  method-complexity:
    config:
      threshold: 256
  method-count:
    config:
      threshold: 32
  method-lines:
    config:
      threshold: 128
  return-statements:
    config:
      threshold: 8

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
