version: "2"
checks:
  argument-count:
    config:
      threshold: 8
  complex-logic:
    config:
      threshold: 8
  file-lines:
    config:
      threshold: 512
  method-complexity:
    config:
      threshold: 16
  method-count:
    config:
      threshold: 32
  method-lines:
    config:
      threshold: 64
  return-statements:
    config:
      threshold: 8
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript:
  editorconfig:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - ".nyc_output/"
  - ".vagrant/"
  - "coverage/"
  - "node_modules/"
  - "test/"
