language: node_js

node_js:
  - node
  - lts/*

env:
  global:
    - CC_TEST_REPORTER_ID=932e9b5ed0961d7e554f5e1e82300779d1f4b42b1718ace27c71516d7aaaf52f

before_script:
  - wget -O ./cctr https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cctr
  - ./cctr before-build

after_script:
  - ./cctr after-build -t lcov --exit-code $TRAVIS_TEST_RESULT

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        - provider: npm
          email: me@mgsisk.com
          api_key:
            secure: dpD84LeDDcDGxj3TYE+sv+kv/uvD2GGKk/oYNr3h2E/BBWNXxxhPzK3zITS2joBc0sI+38RG6iTHcv7mhqTzJkGRNC8fWCfth4wU5Mmfh0FhU0pw77LfbMcBYS9VltYlTazDnOH09a5bNFzHFravUhbTjYpuP92cN+IYUzWHiZvsuQ8q0yDug0ZT54hRhxcyHCEtyivO0DsBmZW3dA+A967S967LduDUNoc21lXo7szLanjBYVVFNrcZSlpjw+3ijoHl/bi92lOUkllXMzrudc7j6WXVBaDwsgbvL2hBK1sTLKyVD+Ln6Yu8c/QCkwPDrAUm6fBcA6Hp4yrjR1RyIFr3njbXh+SeYjyArXO/TbYug8Bt9plwO6M3gv1BJoHF6ZsufuvQKryWjSCKwfjlU8pfwOscygpYkK/vDcUzUHijg/JV1Uk2frV8B1BXXa3h2khyheD9SVpYZRN3Qu83Y8E17TrfnH1fgef4Pm6UmV4LEsMDW1vQcPUOjS/uhaHWloRBbMy/OS92NxWob9UIjzMEzmmedAsaYA6rhK2Epj4px83Sm5gUj7M6uearGQQucV4+7v7m7xzoKD4h+xcp4VNFOukwhemFFARxDOB6wevhYbs3sp7e43WljTg9Qm5O/kb1eXoK6Y59jaazynmbAVhA86hrAlefX3CpRRqZjT4=
          on:
            repo: mgsisk/postcss-modular-rhythm
            tags: true
        - provider: npm
          registry: https://npm.pkg.github.com
          email: me@mgsisk.com
          api_key:
            secure: A5uDvFNf1o2XEIhzdr3w0VWE9AfkT0YegpeU6wS8MyP29qFBHFxLmJ1Xq4efqxcpx7A5mjKS5capZ0atUaO6MNRRKoXEW6WlZ27WhOBGu5ZgJY2FgxfRZmjapnGCy8CK5aIuAlbhZofui6++zDD+2qYF1TmQUUN3SqgP9Hmy2znMhAUbtm0KsMfatNJCRUpkd0IwMYuIRRWVRm2pXW6wIC/BrRBDz11xxwrz238vynodYhPVYVbjVnuR9lM+RFabuNmoYF3mkXYoVJN+iB0fsi5nRVGn5Oy9dew2RFswftaJ7I8TwY5u356Xt8+54xzVqB2Yosv4SywVWxpztBo/AhkyT0d398wTkGAKmkld1c61avz4ObMwvS00h8NfTxDbWo2ZpcHcPAOsLoh+gYR4yMdAXLLDBDKyaQzJX6dZLXEB6qCkTRU/jEqynXNgOv0YY7XPLs/xWbvJQzB1bGoW1pQjLpXFAmVcvE9TIYfC8QsrswrGN7dwApSa74Y6JnUREZDe/lFhnEGiiIubx5RXi80PMiUiSrXxUCcWPwBB1YT/eaxN3gknKyRQ6g3jUw/J5hO0Di5cC4lSebzXb0bqvyC6L3zkiNzXhYVzml/lahrQd2zQq4iERq4zefl+YNJx/LPUYUiHKq5PxlePt7fgE8zRpyVGhjE67glR56xhrus=
          edge:
            branch: master
          on:
            repo: mgsisk/postcss-modular-rhythm
            tags: true
