name: learn-github-actions
on: [push]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm run lint.js

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['latest', 'lts']
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - run: npm test
      - uses: codacy/codacy-coverage-reporter-action@master
        if: ${{ matrix.node == 'latest' }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm -v
